{"trial_id": "1", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "num_layers", "default": null, "conditions": [], "min_value": 1, "max_value": 10, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "neurons0", "default": null, "conditions": [], "min_value": 8, "max_value": 128, "step": 8, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "activation0", "default": "relu", "conditions": [], "values": ["relu", "sgd", "tanh"], "ordered": false}}, {"class_name": "Choice", "config": {"name": "optimizer", "default": "adam", "conditions": [], "values": ["adam", "sgd", "rmsprop", "adadelta", "nadam"], "ordered": false}}], "values": {"num_layers": 2, "neurons0": 16, "activation0": "sgd", "optimizer": "rmsprop"}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"E:\\anaconda\\lib\\site-packages\\keras_tuner\\engine\\base_tuner.py\", line 270, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"E:\\anaconda\\lib\\site-packages\\keras_tuner\\engine\\base_tuner.py\", line 235, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"E:\\anaconda\\lib\\site-packages\\keras_tuner\\engine\\tuner.py\", line 287, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"E:\\anaconda\\lib\\site-packages\\keras_tuner\\engine\\tuner.py\", line 213, in _build_and_fit_model\n    model = self._try_build(hp)\n  File \"E:\\anaconda\\lib\\site-packages\\keras_tuner\\engine\\tuner.py\", line 155, in _try_build\n    model = self._build_hypermodel(hp)\n  File \"E:\\anaconda\\lib\\site-packages\\keras_tuner\\engine\\tuner.py\", line 146, in _build_hypermodel\n    model = self.hypermodel.build(hp)\n  File \"C:\\Users\\ADITYA\\AppData\\Local\\Temp\\ipykernel_9368\\3633499587.py\", line 7, in build_model\n    model.add(Dense(\n  File \"E:\\anaconda\\lib\\site-packages\\keras\\src\\dtensor\\utils.py\", line 96, in _wrap_function\n    init_method(layer_instance, *args, **kwargs)\n  File \"E:\\anaconda\\lib\\site-packages\\keras\\src\\layers\\core\\dense.py\", line 125, in __init__\n    self.activation = activations.get(activation)\n  File \"E:\\anaconda\\lib\\site-packages\\tensorflow\\python\\util\\traceback_utils.py\", line 153, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"E:\\anaconda\\lib\\site-packages\\keras\\src\\activations.py\", line 705, in get\n    return deserialize(identifier, use_legacy_format=use_legacy_format)\n  File \"E:\\anaconda\\lib\\site-packages\\keras\\src\\activations.py\", line 660, in deserialize\n    raise ValueError(\nValueError: Unknown activation function 'sgd' cannot be deserialized.\n"}